#!/bin/sh

if [ "$(uname)" = Darwin ] ; then
  export DYLD_LIBRARY_PATH=$(brew --prefix openssl)/lib:$DYLD_LIBRARY_PATH
elif [ -f /etc/fedora-release ]; then
  export LD_LIBRARY_PATH=/opt/openssl-compat-bitcoin/lib:$LD_LIBRARY_PATH
fi

# if being executed from installation into some base directory,
# we make sure we are running standing at this location
if expr "$0" : '.*/bin/openbazaar$' > /dev/null ; then
  PYBASE=${0%/bin/openbazaar}/share/openbazaar
  (cd "$PYBASE" && python2 -m node.openbazaar "$@") &
else
  # openbazaar not installed in the system, trying local install
  # with virtual environment first
  if [ -f ./env/bin/python2 -a -r ./env/bin/python2 -a -x ./env/bin/python2 ] ; then
    ./env/bin/python2 -m node.openbazaar "$@" &
  else
    python -m node.openbazaar "$@" &
  fi
fi
